import { bloodData } from './blood-operations-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const today=()=>new Date().toISOString().slice(0,10);

export async function mountOperationalSales(root){
 const branches=await bloodData.branches(),bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Ventas / Salidas</h2><div class="muted">Control operativo de salida, facturación y conciliación. No es CRM.</div></div><button id="sale-new">Nueva salida</button></div>
 <div id="sale-msg"></div><div class="grid sales-kpis" id="sale-kpis"></div>
 <section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Código</th><th>Cliente/Centro</th><th>Sucursal</th><th>Factura</th><th>Estado</th><th>Total</th><th>Cobrado</th><th>Pendiente</th></tr></thead><tbody id="sale-body"></tbody></table></div></section>
 <section class="card"><h3>Reporte de ventas/salidas</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Sucursal</th><th>Registros</th><th>Despachadas</th><th>Facturadas</th><th>Cobradas</th><th>Facturado</th><th>Cobrado</th><th>Pendiente</th></tr></thead><tbody id="sale-report"></tbody></table></div></section>
 <dialog id="sale-dialog" class="sales-dialog"><form id="sale-form"><h3>Formulario de venta / salida</h3>
 <label>Código<input id="sale-code" required placeholder="SAL-2026-001"></label><label>Fecha<input id="sale-date" type="date" value="${today()}" required></label>
 <label>Sucursal<select id="sale-branch" required><option value="">Seleccionar…</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label>
 <label>Cliente / Centro<input id="sale-customer" required></label><label>N.º solicitud<input id="sale-request"></label><label>Paciente / Código<input id="sale-patient"></label>
 <label>Factura<input id="sale-invoice"></label><label>Estado<select id="sale-status"><option>DESPACHADA</option><option>FACTURADA</option><option>COBRADA</option><option>PENDIENTE</option></select></label>
 <h4>Detalle</h4><label>Componente<input id="sale-component" required placeholder="Concentrado de hematíes"></label>
 <div class="filter-grid"><label>ABO<select id="sale-abo"><option></option><option>A</option><option>B</option><option>AB</option><option>O</option></select></label><label>Rh<select id="sale-rh"><option></option><option>POSITIVO</option><option>NEGATIVO</option></select></label></div>
 <label>Cantidad<input id="sale-qty" type="number" min="1" value="1" required></label><label>Precio unitario<input id="sale-price" type="number" min="0" step="0.01" value="0"></label><label>Cobrado<input id="sale-collected" type="number" min="0" step="0.01" value="0"></label>
 <label>Notas<textarea id="sale-notes"></textarea></label><div class="dialog-actions"><button type="button" id="sale-cancel" class="secondary">Cancelar</button><button>Guardar salida</button></div></form></dialog>`;
 async function load(){try{const [rows,rep]=await Promise.all([bloodData.sales(),bloodData.salesSummary()]);document.getElementById('sale-body').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.sale_date)}</td><td><code>${esc(r.sale_code)}</code></td><td>${esc(r.customer_name)}</td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.invoice_number||'—')}</td><td>${esc(r.status)}</td><td>${Number(r.total_amount||0).toLocaleString('es-DO')}</td><td>${Number(r.collected_amount||0).toLocaleString('es-DO')}</td><td>${Math.max(Number(r.total_amount||0)-Number(r.collected_amount||0),0).toLocaleString('es-DO')}</td></tr>`).join(''):'<tr><td colspan="9">Sin registros.</td></tr>';
 document.getElementById('sale-report').innerHTML=rep.length?rep.map(r=>`<tr><td>${esc(r.sale_date)}</td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.sale_records)}</td><td>${esc(r.dispatched_records)}</td><td>${esc(r.invoiced_records)}</td><td>${esc(r.collected_records)}</td><td>${Number(r.invoiced_value||0).toLocaleString('es-DO')}</td><td>${Number(r.collected_value||0).toLocaleString('es-DO')}</td><td>${Number(r.pending_value||0).toLocaleString('es-DO')}</td></tr>`).join(''):'<tr><td colspan="9">Sin datos.</td></tr>';
 const t=rep.reduce((a,x)=>({d:a.d+Number(x.sale_records||0),f:a.f+Number(x.invoiced_value||0),c:a.c+Number(x.collected_value||0),p:a.p+Number(x.pending_value||0)}),{d:0,f:0,c:0,p:0});
 document.getElementById('sale-kpis').innerHTML=`<section class="card"><div class="muted">Salidas</div><div class="kpi">${t.d}</div></section><section class="card"><div class="muted">Facturado</div><div class="kpi">RD$${t.f.toLocaleString('es-DO')}</div></section><section class="card"><div class="muted">Cobrado</div><div class="kpi">RD$${t.c.toLocaleString('es-DO')}</div></section><section class="card"><div class="muted">Pendiente</div><div class="kpi">RD$${t.p.toLocaleString('es-DO')}</div></section>`;
 }catch(e){document.getElementById('sale-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Instale SQL v0.23.0.</div>`}}
 document.getElementById('sale-new').onclick=()=>document.getElementById('sale-dialog').showModal();document.getElementById('sale-cancel').onclick=()=>document.getElementById('sale-dialog').close();
 document.getElementById('sale-form').onsubmit=async e=>{e.preventDefault();try{const qty=Number(v('sale-qty')),price=Number(v('sale-price')),total=qty*price,col=Number(v('sale-collected'));await bloodData.createSale({sale_code:v('sale-code'),sale_date:v('sale-date'),branch_id:v('sale-branch'),customer_name:v('sale-customer'),destination_center:v('sale-customer'),request_number:v('sale-request')||null,patient_code:v('sale-patient')||null,invoice_number:v('sale-invoice')||null,status:v('sale-status'),payment_status:col>=total&&total>0?'COBRADA':(col>0?'PARCIAL':'PENDIENTE'),total_amount:total,collected_amount:col,notes:v('sale-notes')||null},[{component_name:v('sale-component'),abo:v('sale-abo')||null,rh:v('sale-rh')||null,quantity:qty,unit_price:price}]);document.getElementById('sale-dialog').close();e.target.reset();await load()}catch(x){document.getElementById('sale-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}};
 function v(id){return document.getElementById(id).value.trim()} await load();
}
