import { bloodData } from './blood-operations-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const today=()=>new Date().toISOString().slice(0,10);

export async function mountProjects(root){
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Gestión de Proyectos</h2><div class="muted">Portafolio de Operaciones, SGC, Compliance, Tecnología y Capacitación.</div></div><button id="pm-new">Nuevo proyecto</button></div><div id="pm-msg"></div>
 <section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Proyecto</th><th>Dominio</th><th>Prioridad</th><th>Estado</th><th>Avance</th><th>Meta</th><th>Tareas</th><th>Vencidas</th></tr></thead><tbody id="pm-body"></tbody></table></div></section>
 <dialog id="pm-dialog" class="sales-dialog"><form id="pm-form"><h3>Nuevo proyecto</h3><label>Código<input id="pm-code" required></label><label>Título<input id="pm-title" required></label><label>Dominio<select id="pm-domain"><option>OPERACIONES</option><option>SGC</option><option>COMPLIANCE</option><option>TECNOLOGIA</option><option>CAPACITACION</option></select></label><label>Prioridad<select id="pm-priority"><option>MEDIA</option><option>ALTA</option><option>CRITICA</option><option>BAJA</option></select></label><label>Fecha inicio<input id="pm-start" type="date"></label><label>Fecha meta<input id="pm-target" type="date"></label><label>Objetivo<textarea id="pm-objective"></textarea></label><label>Resultado esperado<textarea id="pm-result"></textarea></label><div class="dialog-actions"><button type="button" id="pm-cancel" class="secondary">Cancelar</button><button>Guardar</button></div></form></dialog>`;
 async function load(){try{const rows=await bloodData.projects();document.getElementById('pm-body').innerHTML=rows.length?rows.map(r=>`<tr><td><code>${esc(r.project_code)}</code></td><td>${esc(r.title)}</td><td>${esc(r.domain)}</td><td>${esc(r.priority)}</td><td>${esc(r.status)}</td><td>${esc(r.progress_pct)}%</td><td>${esc(r.target_date||'—')}</td><td>${esc(r.tasks)}</td><td>${esc(r.overdue_tasks)}</td></tr>`).join(''):'<tr><td colspan="9">Sin proyectos.</td></tr>'}catch(e){document.getElementById('pm-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Instale SQL v0.23.0.</div>`}}
 document.getElementById('pm-new').onclick=()=>document.getElementById('pm-dialog').showModal();document.getElementById('pm-cancel').onclick=()=>document.getElementById('pm-dialog').close();document.getElementById('pm-form').onsubmit=async e=>{e.preventDefault();try{await bloodData.createProject({project_code:v('pm-code'),title:v('pm-title'),domain:v('pm-domain'),priority:v('pm-priority'),start_date:v('pm-start')||null,target_date:v('pm-target')||null,objective:v('pm-objective')||null,expected_result:v('pm-result')||null,status:'PLANIFICADO'});document.getElementById('pm-dialog').close();e.target.reset();await load()}catch(x){document.getElementById('pm-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}};function v(id){return document.getElementById(id).value.trim()}await load();
}
