import { auditData } from './audit-data.js';
import { commandData } from './command-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function monday(){
 const d=new Date(),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)
}
export async function mountAudit(root){
 const branches=await commandData.branches(),bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Auditoría y Excepciones</h2><div class="muted">Trazabilidad, candidatos automáticos y revisión semanal.</div></div><button id="aud-refresh" class="secondary">Actualizar</button></div>
 <div id="aud-msg"></div><div class="grid sales-kpis" id="aud-kpis"></div>
 <section class="card"><h3>Candidatos a excepción</h3><div class="status info">No se crean automáticamente sin intervención. El usuario decide cuáles convertir en excepción.</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Fuente</th><th>Sucursal</th><th>Referencia</th><th>Dominio</th><th>Severidad</th><th>Descripción</th><th></th></tr></thead><tbody id="cand-body"></tbody></table></div></section>
 <section class="card"><h3>Portafolio de excepciones</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Fecha</th><th>Sucursal</th><th>Dominio</th><th>Severidad</th><th>Estado</th><th>Edad</th><th>Vencida</th><th>Acciones</th></tr></thead><tbody id="exc-body"></tbody></table></div></section>
 <section class="card"><div class="card-head"><h3>Revisión semanal</h3><button id="review-new">Registrar revisión</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Semana</th><th>Sucursal</th><th>Score</th><th>Donantes</th><th>Tamizaje</th><th>Disponibles</th><th>Despachadas</th><th>Excepciones</th><th>Estado</th></tr></thead><tbody id="review-body"></tbody></table></div></section>
 <section class="card"><h3>Bitácora de auditoría</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha/hora</th><th>Sucursal</th><th>Módulo</th><th>Acción</th><th>Entidad</th><th>Referencia</th></tr></thead><tbody id="audit-body"></tbody></table></div></section>
 <dialog id="review-dialog" class="sales-dialog"><form id="review-form"><h3>Revisión semanal</h3><label>Semana inicia<input id="rev-week" type="date" value="${monday()}" required></label><label>Sucursal<select id="rev-branch" required><option value="">Seleccionar…</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label><label>Hallazgos clave<textarea id="rev-findings"></textarea></label><label>Decisiones<textarea id="rev-decisions"></textarea></label><label>Compromisos<textarea id="rev-commitments"></textarea></label><div class="dialog-actions"><button type="button" id="rev-cancel" class="secondary">Cancelar</button><button>Guardar revisión</button></div></form></dialog>`;
 let scoreMap={};
 async function load(){
  try{
    const [cand,exc,audit,reviews,score]=await Promise.all([auditData.candidates(),auditData.exceptions(),auditData.audit(),auditData.reviews(),commandData.scorecard()]);
    scoreMap=Object.fromEntries(score.map(x=>[x.branch_id,x]));
    document.getElementById('cand-body').innerHTML=cand.length?cand.map((r,i)=>`<tr><td>${esc(r.source_type)}</td><td>${esc(bm[r.branch_id]||'General')}</td><td>${esc(r.source_reference||'—')}</td><td>${esc(r.domain)}</td><td>${esc(r.severity)}</td><td>${esc(r.description)}</td><td><button class="secondary compact" data-cand="${i}">Crear excepción</button></td></tr>`).join(''):'<tr><td colspan="7">Sin candidatos.</td></tr>';
    document.getElementById('exc-body').innerHTML=exc.length?exc.map(r=>`<tr><td><code>${esc(r.exception_code)}</code></td><td>${esc(r.exception_date)}</td><td>${esc(bm[r.branch_id]||'General')}</td><td>${esc(r.domain)}</td><td>${esc(r.severity)}</td><td>${esc(r.status)}</td><td>${esc(r.age_days)} d</td><td>${r.overdue?'Sí':'No'}</td><td>${esc(r.completed_actions)}/${esc(r.actions_count)}</td></tr>`).join(''):'<tr><td colspan="9">Sin excepciones.</td></tr>';
    document.getElementById('review-body').innerHTML=reviews.length?reviews.map(r=>`<tr><td>${esc(r.week_start)}</td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.management_score??'—')}</td><td>${esc(r.donors)}</td><td>${esc(r.screened_units)}</td><td>${esc(r.available_units)}</td><td>${esc(r.dispatched_units)}</td><td>${esc(r.open_exceptions)}</td><td>${esc(r.status)}</td></tr>`).join(''):'<tr><td colspan="9">Sin revisiones.</td></tr>';
    document.getElementById('audit-body').innerHTML=audit.length?audit.map(r=>`<tr><td>${esc(new Date(r.event_time).toLocaleString('es-DO'))}</td><td>${esc(bm[r.branch_id]||'General')}</td><td>${esc(r.module)}</td><td>${esc(r.action)}</td><td>${esc(r.entity_table||'—')}</td><td>${esc(r.entity_reference||'—')}</td></tr>`).join(''):'<tr><td colspan="6">Sin eventos.</td></tr>';
    const crit=exc.filter(x=>x.severity==='CRITICA'&&['ABIERTA','EN_TRATAMIENTO'].includes(x.status)).length,over=exc.filter(x=>x.overdue).length;
    document.getElementById('aud-kpis').innerHTML=`<section class="card"><div class="muted">Candidatos</div><div class="kpi">${cand.length}</div></section><section class="card"><div class="muted">Excepciones abiertas</div><div class="kpi">${exc.filter(x=>['ABIERTA','EN_TRATAMIENTO'].includes(x.status)).length}</div></section><section class="card"><div class="muted">Críticas</div><div class="kpi">${crit}</div></section><section class="card"><div class="muted">Vencidas</div><div class="kpi">${over}</div></section>`;
    document.querySelectorAll('[data-cand]').forEach(b=>b.onclick=async()=>{try{await auditData.createCandidateException(cand[Number(b.dataset.cand)]);await load()}catch(x){document.getElementById('aud-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}});
    document.getElementById('aud-msg').innerHTML='';
  }catch(e){document.getElementById('aud-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Ejecute sql/27_AUDIT_TRACE_EXCEPTIONS_v0_27.sql.</div>`}
 }
 document.getElementById('aud-refresh').onclick=load;document.getElementById('review-new').onclick=()=>document.getElementById('review-dialog').showModal();document.getElementById('rev-cancel').onclick=()=>document.getElementById('review-dialog').close();
 document.getElementById('review-form').onsubmit=async e=>{e.preventDefault();try{const branch=document.getElementById('rev-branch').value,sc=scoreMap[branch]||{};await auditData.createReview({week_start:document.getElementById('rev-week').value,branch_id:branch,management_score:sc.management_score??null,donors:sc.donors||0,effective_donations:sc.effective_donations||0,screened_units:sc.screened_units||0,released_units:0,available_units:sc.available_units||0,dispatched_units:sc.dispatched_units||0,invoiced_amount:sc.invoiced_amount||0,red_stock:sc.red_stock||0,open_quality_actions:sc.open_quality_actions||0,open_exceptions:sc.open_exceptions||0,overdue_actions:0,key_findings:document.getElementById('rev-findings').value.trim()||null,decisions:document.getElementById('rev-decisions').value.trim()||null,commitments:document.getElementById('rev-commitments').value.trim()||null,status:'BORRADOR'});document.getElementById('review-dialog').close();e.target.reset();await load()}catch(x){document.getElementById('aud-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}};
 await load();
}
