import { bloodData } from './blood-operations-data.js';
import { flowData } from './blood-flow-data.js';
import { supplyData } from './supply-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const today=()=>new Date().toISOString().slice(0,10);

export async function mountBI(root){
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Inteligencia de Negocios</h2><div class="muted">Operaciones, sangre, tamizaje, salidas y calidad.</div></div></div><div id="bi-msg"></div><div class="grid sales-kpis" id="bi-kpis"></div>
 <section class="card"><h3>Comparativo por sucursal — hoy</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Sucursal</th><th>Donantes</th><th>Donaciones efectivas</th><th>Tamizajes</th><th>Reactivos</th><th>Unidades disponibles</th><th>Salidas</th><th>Facturado</th></tr></thead><tbody id="bi-table"></tbody></table></div></section>
 <section class="card"><h3>Embudo sanguíneo 30 días</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Sucursal</th><th>Donantes</th><th>Efectivas</th><th>Recolectadas</th><th>Tamizadas</th><th>Liberadas</th><th>Disponibles</th><th>Despachadas</th></tr></thead><tbody id="bi-funnel"></tbody></table></div></section>
 <section class="card"><h3>Abastecimiento</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Sucursal</th><th>Componente</th><th>ABO</th><th>Rh</th><th>Disponible</th><th>Cobertura</th><th>Necesarias</th><th>Estado</th></tr></thead><tbody id="bi-supply"></tbody></table></div></section><section class="card"><h3>Indicadores de gestión</h3><ul><li>Tasa de donación efectiva = donaciones efectivas / donantes.</li><li>Tasa reactiva = resultados reactivos / pruebas realizadas.</li><li>Cobertura operativa = inventario disponible vs salidas.</li><li>Conversión despacho→facturación y cartera pendiente.</li><li>NC/CAPA y proyectos se mantienen en sus módulos de SGC/PM.</li></ul></section>`;
 try{const [rows,funnel,supply]=await Promise.all([bloodData.biToday(),flowData.funnel(),supplyData.plan()]);const totals=rows.reduce((a,x)=>({d:a.d+Number(x.donors||0),e:a.e+Number(x.effective_donations||0),s:a.s+Number(x.screened_tests||0),r:a.r+Number(x.reactive_tests||0),i:a.i+Number(x.available_blood_units||0),o:a.o+Number(x.sales_outflows||0),f:a.f+Number(x.invoiced_amount||0)}),{d:0,e:0,s:0,r:0,i:0,o:0,f:0});
 document.getElementById('bi-kpis').innerHTML=`<section class="card"><div class="muted">Donantes</div><div class="kpi">${totals.d}</div></section><section class="card"><div class="muted">Tamizajes</div><div class="kpi">${totals.s}</div></section><section class="card"><div class="muted">Unidades disponibles</div><div class="kpi">${totals.i}</div></section><section class="card"><div class="muted">Facturado hoy</div><div class="kpi">RD$${totals.f.toLocaleString('es-DO')}</div></section>`;
 document.getElementById('bi-supply').innerHTML=supply.length?supply.map(r=>`<tr><td>${esc(r.branch_id)}</td><td>${esc(r.component_name)}</td><td>${esc(r.abo||'—')}</td><td>${esc(r.rh||'—')}</td><td>${esc(r.available_units)}</td><td>${esc(r.coverage_days??'—')}</td><td>${esc(r.required_units)}</td><td>${esc(r.stock_status)}</td></tr>`).join(''):'<tr><td colspan="8">Sin plan de abastecimiento.</td></tr>';
 document.getElementById('bi-funnel').innerHTML=funnel.length?funnel.map(r=>`<tr><td>${esc(r.branch_name)}</td><td>${esc(r.donors)}</td><td>${esc(r.effective_donations)}</td><td>${esc(r.collected_units)}</td><td>${esc(r.screened_units)}</td><td>${esc(r.released_units)}</td><td>${esc(r.available_units)}</td><td>${esc(r.dispatched_units)}</td></tr>`).join(''):'<tr><td colspan="8">Sin datos.</td></tr>';
 document.getElementById('bi-table').innerHTML=rows.map(r=>`<tr><td>${esc(r.branch_name)}</td><td>${esc(r.donors)}</td><td>${esc(r.effective_donations)}</td><td>${esc(r.screened_tests)}</td><td>${esc(r.reactive_tests)}</td><td>${esc(r.available_blood_units)}</td><td>${esc(r.sales_outflows)}</td><td>${Number(r.invoiced_amount||0).toLocaleString('es-DO')}</td></tr>`).join('');
 }catch(e){document.getElementById('bi-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Instale SQL v0.23.0.</div>`}
}
