import { commandData } from './command-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
export async function mountCommandCenter(root){
 const branches=await commandData.branches(),bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Centro de Mando</h2><div class="muted">Supervisión gerencial, score, excepciones y acciones. El cierre operativo se realiza desde Cierre diario.</div></div><button id="cmd-refresh" class="secondary">Actualizar</button></div>
 <div id="cmd-msg"></div><div class="grid sales-kpis" id="cmd-kpis"></div>
 <section class="card"><h3>Scorecard por sucursal</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Sucursal</th><th>Score</th><th>Estado</th><th>Stock rojo</th><th>Alertas críticas</th><th>Acciones SGC</th><th>Excepciones críticas</th><th>Facturado hoy</th></tr></thead><tbody id="score-body"></tbody></table></div></section>
 <section class="card"><div class="card-head"><div><h3>Estado del cierre operativo</h3><div class="muted">Vista de control; no vuelve a capturar datos.</div></div><a class="secondary" href="#dailyinventory">Abrir cierre diario</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Sucursal</th><th>Donantes</th><th>Efectivas</th><th>Tamizadas</th><th>Reactivos</th><th>Liberadas</th><th>Producción</th><th>Disponibles</th><th>Despachadas</th><th>Facturado</th><th>Cierre</th></tr></thead><tbody id="close-body"></tbody></table></div></section>
 <section class="card"><div class="card-head"><h3>Excepciones</h3><button id="ex-new">Nueva excepción</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Código</th><th>Sucursal</th><th>Dominio</th><th>Severidad</th><th>Título</th><th>Estado</th><th>Vence</th></tr></thead><tbody id="ex-body"></tbody></table></div></section>
 <section class="card"><div class="card-head"><h3>Plan de acción</h3><button id="act-new">Nueva acción</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Sucursal</th><th>Acción</th><th>Prioridad</th><th>Estado</th><th>Avance</th><th>Vence</th><th>Vencida</th></tr></thead><tbody id="act-body"></tbody></table></div></section>
 <dialog id="ex-dialog" class="sales-dialog"><form id="ex-form"><h3>Nueva excepción</h3><label>Código<input id="ex-code" required placeholder="EX-2026-001"></label><label>Sucursal<select id="ex-branch"><option value="">General</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label><label>Dominio<select id="ex-domain"><option>DONANTES</option><option>TAMIZAJE</option><option>PRODUCCION</option><option>INVENTARIO</option><option>DESPACHO</option><option>VENTAS</option><option>SGC</option><option>COMPLIANCE</option><option>PROYECTO</option></select></label><label>Severidad<select id="ex-sev"><option>MEDIA</option><option>ALTA</option><option>CRITICA</option><option>BAJA</option></select></label><label>Título<input id="ex-title" required></label><label>Descripción<textarea id="ex-desc" required></textarea></label><label>Vence<input id="ex-due" type="date"></label><div class="dialog-actions"><button type="button" id="ex-cancel" class="secondary">Cancelar</button><button>Guardar</button></div></form></dialog>
 <dialog id="act-dialog" class="sales-dialog"><form id="act-form"><h3>Nueva acción</h3><label>Código<input id="act-code" required placeholder="ACT-2026-001"></label><label>Sucursal<select id="act-branch"><option value="">General</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label><label>Acción<input id="act-title" required></label><label>Objetivo<textarea id="act-objective"></textarea></label><label>Prioridad<select id="act-priority"><option>MEDIA</option><option>ALTA</option><option>CRITICA</option><option>BAJA</option></select></label><label>Vence<input id="act-due" type="date"></label><div class="dialog-actions"><button type="button" id="act-cancel" class="secondary">Cancelar</button><button>Guardar</button></div></form></dialog>`;
 async function load(){try{const [sc,rec,ex,act]=await Promise.all([commandData.scorecard(),commandData.reconciliation(),commandData.exceptions(),commandData.actions()]);
 document.getElementById('score-body').innerHTML=sc.length?sc.map(r=>`<tr><td>${esc(r.branch_name)}</td><td><strong>${esc(r.management_score)}</strong></td><td>${esc(r.management_status)}</td><td>${esc(r.red_stock)}</td><td>${esc(r.critical_alerts)}</td><td>${esc(r.open_quality_actions)}</td><td>${esc(r.critical_exceptions)}</td><td>${Number(r.invoiced_amount||0).toLocaleString('es-DO')}</td></tr>`).join(''):'<tr><td colspan="8">Sin datos.</td></tr>';
 document.getElementById('close-body').innerHTML=rec.length?rec.map(r=>`<tr><td>${esc(r.branch_name)}</td><td>${esc(r.donors)}</td><td>${esc(r.effective_donations)}</td><td>${esc(r.screened_units)}</td><td>${esc(r.reactive_results)}</td><td>${esc(r.released_units)}</td><td>${esc(r.produced_units)}</td><td>${esc(r.available_units)}</td><td>${esc(r.dispatched_units)}</td><td>${Number(r.invoiced_amount||0).toLocaleString('es-DO')}</td><td>${esc(r.close_status||'ABIERTO')}</td></tr>`).join(''):'<tr><td colspan="11">Sin datos.</td></tr>';
 document.getElementById('ex-body').innerHTML=ex.length?ex.map(r=>`<tr><td>${esc(r.exception_date)}</td><td><code>${esc(r.exception_code)}</code></td><td>${esc(bm[r.branch_id]||'General')}</td><td>${esc(r.domain)}</td><td>${esc(r.severity)}</td><td>${esc(r.title)}</td><td>${esc(r.status)}</td><td>${esc(r.due_date||'—')}</td></tr>`).join(''):'<tr><td colspan="8">Sin excepciones.</td></tr>';
 document.getElementById('act-body').innerHTML=act.length?act.map(r=>`<tr><td><code>${esc(r.action_code)}</code></td><td>${esc(bm[r.branch_id]||'General')}</td><td>${esc(r.title)}</td><td>${esc(r.priority)}</td><td>${esc(r.status)}</td><td>${esc(r.progress_pct)}%</td><td>${esc(r.due_date||'—')}</td><td>${r.overdue?'Sí':'No'}</td></tr>`).join(''):'<tr><td colspan="8">Sin acciones.</td></tr>';
 const red=sc.filter(x=>x.management_status==='ROJO').length,crit=ex.filter(x=>x.severity==='CRITICA'&&['ABIERTA','EN_TRATAMIENTO'].includes(x.status)).length,over=act.filter(x=>x.overdue).length,avg=sc.length?Math.round(sc.reduce((a,x)=>a+Number(x.management_score||0),0)/sc.length):0;
 document.getElementById('cmd-kpis').innerHTML=`<section class="card"><div class="muted">Score promedio</div><div class="kpi">${avg}</div></section><section class="card"><div class="muted">Sucursales rojas</div><div class="kpi">${red}</div></section><section class="card"><div class="muted">Excepciones críticas</div><div class="kpi">${crit}</div></section><section class="card"><div class="muted">Acciones vencidas</div><div class="kpi">${over}</div></section>`;
 document.getElementById('cmd-msg').innerHTML='';
 }catch(e){document.getElementById('cmd-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Ejecute sql/26_COMMAND_CENTER_DAILY_CLOSE_v0_26.sql.</div>`}}
 const q=id=>document.getElementById(id);q('cmd-refresh').onclick=load;q('ex-new').onclick=()=>q('ex-dialog').showModal();q('ex-cancel').onclick=()=>q('ex-dialog').close();q('act-new').onclick=()=>q('act-dialog').showModal();q('act-cancel').onclick=()=>q('act-dialog').close();
 q('ex-form').onsubmit=async e=>{e.preventDefault();try{await commandData.createException({exception_code:q('ex-code').value.trim(),branch_id:q('ex-branch').value||null,domain:q('ex-domain').value,severity:q('ex-sev').value,title:q('ex-title').value.trim(),description:q('ex-desc').value.trim(),due_date:q('ex-due').value||null,status:'ABIERTA'});q('ex-dialog').close();e.target.reset();await load()}catch(x){q('cmd-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}};
 q('act-form').onsubmit=async e=>{e.preventDefault();try{await commandData.createAction({action_code:q('act-code').value.trim(),branch_id:q('act-branch').value||null,title:q('act-title').value.trim(),objective:q('act-objective').value.trim()||null,priority:q('act-priority').value,due_date:q('act-due').value||null,status:'PENDIENTE'});q('act-dialog').close();e.target.reset();await load()}catch(x){q('cmd-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}};
 await load();
}
