import { loadDispatchWorkspace, getProductsForDispatch } from './dispatch-data.js';
import { getBranches } from './sales-data.js';
import { commandData } from './command-data.js';

const num=new Intl.NumberFormat('es-DO',{maximumFractionDigits:2});
function esc(value=''){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function defaultDates(){const today=new Date(),to=today.toISOString().slice(0,10),d=new Date(today);d.setDate(d.getDate()-7);return {from:d.toISOString().slice(0,10),to}}
function reconRows(rows,branchMap,productMap){if(!rows.length)return`<tr><td colspan="7" class="muted">No hay diferencias visibles.</td></tr>`;return rows.map(r=>`<tr><td>${esc(r.dispatch_date||'')}</td><td>${esc(branchMap[r.branch_id]?.name||r.branch_id||'')}</td><td>${esc(productMap[r.product_id]?.name||productMap[r.product_id]?.code||r.product_id||'')}</td><td class="num">${num.format(Number(r.dispatched_sale_units||0))}</td><td class="num">${num.format(Number(r.recognized_sale_units||0))}</td><td class="num"><strong>${num.format(Number(r.difference_units||0))}</strong></td><td>${Number(r.difference_units||0)===0?'<span class="status ok">OK</span>':'<span class="status warn">Revisar</span>'}</td></tr>`).join('')}

export async function mountDispatches(root){
 const dates=defaultDates();
 try{
  const [branches,products]=await Promise.all([getBranches(),getProductsForDispatch()]);const branchMap=Object.fromEntries(branches.map(b=>[b.id,b])),productMap=Object.fromEntries(products.map(p=>[p.id,p]));
  root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Despachos consolidados</h2><div class="muted">La captura individual de despachos está inactiva durante la digitalización del proceso actual. Registre el despacho consolidado por destino, grupo, componente y cantidad.</div></div><a class="secondary" href="#dailyinventory">Capturar despachos del día</a></div>
  <div id="dispatch-errors"></div>
  <section class="card quick-capture"><div class="quick-capture-head"><div><div class="eyebrow">Modelo vigente</div><h3>Despacho diario consolidado</h3></div><span class="state-pill state-info">CAPTURA MANUAL</span></div><p class="muted">No capture una fila por cada unidad sanguínea. Use una fila consolidada por destino/componente en el Reporte Operativo Diario.</p></section>
  <section class="card"><div class="card-head"><h3>Despachos manuales recientes</h3><span class="muted">Fuente: Reporte Operativo Diario</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Sucursal</th><th>Destino</th><th>Grupo</th><th>Componente</th><th>Cantidad</th><th>Observación</th></tr></thead><tbody id="dispatch-manual"></tbody></table></div></section>
  <details class="card"><summary><strong>Conciliación técnica histórica — solo consulta</strong></summary><div class="filter-grid"><label>Desde<input id="dispatch-from" type="date" value="${dates.from}"></label><label>Hasta<input id="dispatch-to" type="date" value="${dates.to}"></label><label>Sucursal<select id="dispatch-branch"><option value="">Todas</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label></div><button id="dispatch-search" class="secondary">Actualizar conciliación</button><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Sucursal</th><th>Producto</th><th>Despachado</th><th>Venta reconocida</th><th>Diferencia</th><th>Estado</th></tr></thead><tbody id="recon-body"></tbody></table></div></details>`;

  async function loadManual(){try{const reports=await commandData.recentCloses(30),rows=[];for(const r of reports){for(const d of (Array.isArray(r.manual_dispatches)?r.manual_dispatches:[])){rows.push({...d,date:r.close_date,branch_id:r.branch_id})}}document.getElementById('dispatch-manual').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(branchMap[r.branch_id]?.name||r.branch_id)}</td><td>${esc(r.destination||'—')}</td><td>${esc(r.group||'—')}</td><td>${esc(r.component||'—')}</td><td><strong>${esc(r.quantity||0)}</strong></td><td>${esc(r.note||'—')}</td></tr>`).join(''):'<tr><td colspan="7">Sin despachos manuales registrados.</td></tr>'}catch(e){document.getElementById('dispatch-errors').innerHTML=`<div class="status warn">${esc(e.message)}</div>`}}
  async function loadRecon(){try{const filters={from:document.getElementById('dispatch-from').value,to:document.getElementById('dispatch-to').value,branchId:document.getElementById('dispatch-branch').value};const ws=await loadDispatchWorkspace(filters);const rows=(ws.reconciliation||[]).filter(r=>Number(r.difference_units||0)!==0);document.getElementById('recon-body').innerHTML=reconRows(rows,branchMap,productMap)}catch(e){document.getElementById('dispatch-errors').innerHTML=`<div class="status warn">${esc(e.message)}</div>`}}
  document.getElementById('dispatch-search').onclick=loadRecon;await loadManual();await loadRecon();
 }catch(error){root.innerHTML=`<section class="card"><h3>Despachos no disponible</h3><div class="status bad">${esc(error.message)}</div></section>`}
}
