import { bloodData } from './blood-operations-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const today=()=>new Date().toISOString().slice(0,10);
const stamp=(prefix)=>`${prefix}-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}`;

export async function mountDonors(root){
 const branches=await bloodData.branches(); const bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 let donors=[];
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Donantes y donación rápida</h2><div class="muted">Busca primero. Captura solo lo necesario y reutiliza el contexto disponible.</div></div><button id="don-new">Nuevo donante</button></div>
 <div id="don-msg"></div>
 <section class="card quick-capture"><div class="quick-capture-head"><div><div class="eyebrow">Paso 1</div><h3>Buscar donante</h3></div></div><div class="quick-search"><input id="don-search" type="search" placeholder="Código de donante" autocomplete="off"><button id="don-search-btn" class="secondary">Buscar</button></div><div id="don-search-result" class="muted">Escribe un código para buscar antes de crear un registro nuevo.</div></section>
 <div class="grid sales-kpis" id="don-kpis"></div>
 <section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Código</th><th>Sucursal</th><th>Tipo</th><th>ABO</th><th>Rh</th><th>Estado</th><th>Acción</th></tr></thead><tbody id="don-body"></tbody></table></div></section>
 <dialog id="don-dialog" class="sales-dialog"><form id="don-form"><h3>Nuevo donante</h3><p class="muted">Los datos administrativos se generan automáticamente. Completa primero los datos operativos.</p>
 <label>Sucursal<select id="don-branch" required><option value="">Seleccionar…</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label>
 <label>Tipo<select id="don-type"><option>VOLUNTARIO</option><option>REPOSICION</option><option>DIRIGIDO</option></select></label>
 <div class="filter-grid"><label>ABO<select id="don-abo"><option value="">Pendiente</option><option>A</option><option>B</option><option>AB</option><option>O</option></select></label><label>Rh<select id="don-rh"><option value="">Pendiente</option><option>POSITIVO</option><option>NEGATIVO</option></select></label></div>
 <label>Evaluación<select id="don-status"><option>ACEPTADO</option><option>DIFERIDO</option></select></label>
 <label id="don-reason-wrap" hidden>Motivo del diferimiento<input id="don-reason"></label>
 <details class="advanced-fields"><summary>Datos adicionales</summary><label>Código<input id="don-code"></label><label>Fecha<input id="don-date" type="date"></label><label><input id="don-effective" type="checkbox"> Marcar donación efectiva</label><label>Observaciones<textarea id="don-notes"></textarea></label></details>
 <div class="dialog-actions"><button type="button" id="don-cancel" class="secondary">Cancelar</button><button>Guardar donante</button></div></form></dialog>
 <dialog id="donation-dialog" class="sales-dialog"><form id="donation-form"><h3>Registrar donación</h3><div id="donation-person" class="status info"></div>
 <label>Sucursal<select id="donation-branch" required><option value="">Seleccionar…</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label>
 <label>Unidad origen<input id="donation-unit" required placeholder="Escanee o escriba el código de bolsa"></label>
 <label>Unidades recolectadas<input id="donation-qty" type="number" min="0" step="1" value="1" required></label>
 <details class="advanced-fields"><summary>Datos adicionales</summary><label>Código donación<input id="donation-code"></label><label>Fecha<input id="donation-date" type="date"></label><label><input id="donation-effective" type="checkbox" checked> Recolección efectiva</label><label>Observaciones<textarea id="donation-notes"></textarea></label></details>
 <div class="dialog-actions"><button type="button" id="donation-cancel" class="secondary">Cancelar</button><button>Guardar donación</button></div></form></dialog>`;
 let selectedDonor=null;
 function defaultBranch(selectId,donor){const el=document.getElementById(selectId); if(donor?.branch_id) el.value=donor.branch_id; else if(branches.length===1) el.value=branches[0].id}
 function openDonation(donor){selectedDonor=donor;document.getElementById('donation-form').reset();document.getElementById('donation-person').textContent=`${donor.donor_code} · ${donor.abo||'ABO pendiente'} ${donor.rh||''}`;defaultBranch('donation-branch',donor);document.getElementById('donation-qty').value='1';document.getElementById('donation-effective').checked=true;document.getElementById('donation-code').value=stamp('DONACION');document.getElementById('donation-date').value=today();document.getElementById('donation-dialog').showModal()}
 function renderSearch(){const q=document.getElementById('don-search').value.trim().toLowerCase();const box=document.getElementById('don-search-result');if(!q){box.textContent='Escribe un código para buscar antes de crear un registro nuevo.';return}const found=donors.filter(r=>String(r.donor_code||'').toLowerCase().includes(q)).slice(0,5);box.innerHTML=found.length?found.map(r=>`<div class="search-result-row"><div><strong>${esc(r.donor_code)}</strong><span>${esc(bm[r.branch_id]||'')} · ${esc(r.status)}</span></div><button class="compact" data-donate="${esc(r.id)}">Registrar donación</button></div>`).join(''):`<div class="status info">No se encontró el código. <button id="don-create-from-search" class="secondary compact">Crear nuevo</button></div>`;box.querySelectorAll('[data-donate]').forEach(b=>b.onclick=()=>openDonation(donors.find(r=>r.id===b.dataset.donate)));box.querySelector('#don-create-from-search')?.addEventListener('click',()=>openNew())}
 function openNew(){const f=document.getElementById('don-form');f.reset();document.getElementById('don-code').value=stamp('DON');document.getElementById('don-date').value=today();document.getElementById('don-reason-wrap').hidden=true;defaultBranch('don-branch');document.getElementById('don-dialog').showModal()}
 async function load(){try{const [rows,sum]=await Promise.all([bloodData.donors(),bloodData.donorSummary()]);donors=rows;document.getElementById('don-body').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.registration_date)}</td><td><code>${esc(r.donor_code)}</code></td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.donor_type)}</td><td>${esc(r.abo||'—')}</td><td>${esc(r.rh||'—')}</td><td>${esc(r.status)}</td><td><button class="secondary compact" data-row-donate="${esc(r.id)}">Donación</button></td></tr>`).join(''):'<tr><td colspan="8">Sin donantes.</td></tr>';document.querySelectorAll('[data-row-donate]').forEach(b=>b.onclick=()=>openDonation(donors.find(r=>r.id===b.dataset.rowDonate)));
 const total=sum.reduce((a,x)=>a+Number(x.total_donors||0),0), eff=sum.reduce((a,x)=>a+Number(x.effective_donations||0),0), def=sum.reduce((a,x)=>a+Number(x.deferred_donors||0),0);document.getElementById('don-kpis').innerHTML=`<section class="card"><div class="muted">Donantes</div><div class="kpi">${total}</div></section><section class="card"><div class="muted">Efectivos</div><div class="kpi">${eff}</div></section><section class="card"><div class="muted">Diferidos</div><div class="kpi">${def}</div></section>`;renderSearch()}catch(e){document.getElementById('don-msg').innerHTML=`<div class="status warn">${esc(e.message)} · Instale SQL v0.23.0.</div>`}}
 document.getElementById('don-new').onclick=openNew;document.getElementById('don-cancel').onclick=()=>document.getElementById('don-dialog').close();document.getElementById('donation-cancel').onclick=()=>document.getElementById('donation-dialog').close();document.getElementById('don-search-btn').onclick=renderSearch;document.getElementById('don-search').addEventListener('input',renderSearch);document.getElementById('don-status').onchange=e=>document.getElementById('don-reason-wrap').hidden=e.target.value!=='DIFERIDO';
 document.getElementById('don-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const status=val('don-status');await bloodData.createDonor({donor_code:val('don-code')||stamp('DON'),branch_id:val('don-branch'),donor_type:val('don-type'),abo:val('don-abo')||null,rh:val('don-rh')||null,status,deferral_reason:status==='DIFERIDO'?(val('don-reason')||null):null,effective_donation:document.getElementById('don-effective').checked,observations:val('don-notes')||null,registration_date:val('don-date')||today()});document.getElementById('don-dialog').close();await load()}catch(x){document.getElementById('don-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}finally{button.disabled=false}};
 document.getElementById('donation-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{if(!selectedDonor)throw new Error('Seleccione un donante');await bloodData.createDonation({donation_code:val('donation-code')||stamp('DONACION'),donor_id:selectedDonor.id,branch_id:val('donation-branch'),donation_date:val('donation-date')||today(),collection_effective:document.getElementById('donation-effective').checked,collected_units:Number(val('donation-qty')||1),source_unit_code:val('donation-unit'),status:'RECOLECTADA',observations:val('donation-notes')||null});document.getElementById('donation-dialog').close();document.getElementById('don-msg').innerHTML='<div class="status ok">Donación registrada. La unidad queda en estado RECOLECTADA.</div>';await load()}catch(x){document.getElementById('don-msg').innerHTML=`<div class="status bad">${esc(x.message)}</div>`}finally{button.disabled=false}};
 function val(id){return document.getElementById(id).value.trim()} await load();
}
