import { routeList,getRoute,getRouteMeta,navigate } from './router.js';
import { renderView } from './views.js';
import { mountOpsDashboard } from './ops-dashboard.js';
import { mountOperationalSales } from './operational-sales.js';
import { mountDonors } from './donors.js';
import { mountScreening } from './screening.js';
import { mountBloodFlow } from './blood-flow.js';
import { mountProduction } from './production.js';
import { mountSupplyPlanning } from './supply-planning.js';
import { mountBloodInventory } from './blood-inventory.js';
import { mountDispatches } from './dispatch.js';
import { mountInventory } from './inventory.js';
import { mountRequisitions } from './requisitions.js';
import { mountInspections } from './inspections.js';
import { mountPlanning } from './planning.js';
import { mountQuality } from './quality.js';
import { mountDocuments } from './documents.js';
import { mountCompliance } from './compliance.js';
import { mountBI } from './bi.js';
import { mountProjects } from './projects.js';
import { mountSettings } from './settings.js';
import { mountQA } from './qa.js';
import { signOut } from './auth.js';
export function mountLayout(session){
 const app=document.getElementById('app'),nav=routeList().map(([k,m])=>`<button data-route="${k}">${m.title}</button>`).join('');
 app.innerHTML=`<div class="app-layout"><aside class="sidebar" id="sidebar"><div class="sidebar-brand"><div class="brand-mark">H</div><div><strong>HemoCura</strong><br><small>Operaciones · Sangre · SGC</small></div></div><nav class="nav">${nav}</nav></aside><section class="main-shell"><header class="topbar"><div><button class="mobile-toggle secondary" id="menu-btn">☰</button><strong id="page-title">Centro de Operaciones</strong><div class="muted" id="page-subtitle"></div></div><div class="topbar-actions"><span class="muted">${session.user?.email||'Usuario'}</span><button id="logout-btn">Salir</button></div></header><main class="content"><div id="view"></div></main></section></div>`;
 document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.getElementById('logout-btn').onclick=async()=>{await signOut();location.replace('./login.html')};document.getElementById('menu-btn')?.addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
 const render=async()=>{const r=getRoute(),m=getRouteMeta(r);document.getElementById('page-title').textContent=m.title;document.getElementById('page-subtitle').textContent=m.subtitle;document.getElementById('view').innerHTML=renderView(r);document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===r));document.getElementById('sidebar').classList.remove('open');
 const mounts={dashboard:()=>mountOpsDashboard(document.getElementById('ops-dashboard-root')),sales:()=>mountOperationalSales(document.getElementById('sales-root')),donors:()=>mountDonors(document.getElementById('donors-root')),screening:()=>mountScreening(document.getElementById('screening-root')),bloodflow:()=>mountBloodFlow(document.getElementById('bloodflow-root')),production:()=>mountProduction(document.getElementById('production-root')),supply:()=>mountSupplyPlanning(document.getElementById('supply-root')),bloodinventory:()=>mountBloodInventory(document.getElementById('bloodinventory-root')),dispatches:()=>mountDispatches(document.getElementById('dispatch-root')),inventory:()=>mountInventory(document.getElementById('inventory-root')),requisitions:()=>mountRequisitions(document.getElementById('requisitions-root')),inspections:()=>mountInspections(document.getElementById('inspections-root')),planning:()=>mountPlanning(document.getElementById('planning-root')),quality:()=>mountQuality(document.getElementById('quality-root')),documents:()=>mountDocuments(document.getElementById('documents-root')),compliance:()=>mountCompliance(document.getElementById('compliance-root')),bi:()=>mountBI(document.getElementById('bi-root')),projects:()=>mountProjects(document.getElementById('projects-root')),settings:()=>mountSettings(document.getElementById('settings-root')),qa:()=>mountQA(document.getElementById('qa-root'))};if(mounts[r])await mounts[r]();};
 window.addEventListener('hashchange',()=>render().catch(e=>console.error('[HEMOCURA_NAV_ERROR]',e)));render().catch(e=>console.error('[HEMOCURA_NAV_ERROR]',e));
}
