import { bloodData } from './blood-operations-data.js';
import { commandData } from './command-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

export async function mountScreening(root){
 const branches=await bloodData.branches(),bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Tamizaje por lotes</h2><div class="muted">La captura individual de resultados está inactiva. El trabajo operativo se registra por lote/tanda en el Reporte Operativo Diario.</div></div><a class="secondary" href="#dailyinventory">Abrir reporte diario</a></div>
 <div id="scr-msg"></div>
 <section class="card quick-capture"><div class="quick-capture-head"><div><div class="eyebrow">Modelo vigente</div><h3>Lotes diarios</h3></div><span class="state-pill state-info">CAPTURA CONSOLIDADA</span></div><p class="muted">Registre por lote: recibidos, no reactivos, reactivos, pendientes y descartados. No se solicita una fila por cada unidad.</p></section>
 <section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Sucursal</th><th>Lote / tanda</th><th>Recibidos</th><th>No reactivos</th><th>Reactivos</th><th>Pendientes</th><th>Descartados</th></tr></thead><tbody id="scr-lots"></tbody></table></div></section>
 <details class="card"><summary><strong>Histórico técnico individual — solo consulta</strong></summary><p class="muted">Se conserva para trazabilidad histórica; no es el flujo operativo principal.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Unidad</th><th>Sucursal</th><th>Prueba</th><th>Resultado</th><th>Reactivo/Lote</th><th>Estado</th></tr></thead><tbody id="scr-body"></tbody></table></div></details>`;
 async function load(){try{const [reports,legacy]=await Promise.all([commandData.recentCloses(30),bloodData.screenings()]);const lotRows=[];for(const r of reports){for(const l of (Array.isArray(r.screening_lots)?r.screening_lots:[])){lotRows.push({...l,date:r.close_date,branch_id:r.branch_id})}}document.getElementById('scr-lots').innerHTML=lotRows.length?lotRows.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(bm[x.branch_id]||x.branch_id)}</td><td><strong>${esc(x.lot||'—')}</strong></td><td>${esc(x.received||0)}</td><td>${esc(x.non_reactive||0)}</td><td>${esc(x.reactive||0)}</td><td>${esc(x.pending||0)}</td><td>${esc(x.discarded||0)}</td></tr>`).join(''):'<tr><td colspan="8">Sin lotes diarios registrados.</td></tr>';document.getElementById('scr-body').innerHTML=legacy.length?legacy.map(r=>`<tr><td>${esc(r.screening_date)}</td><td><code>${esc(r.source_unit_code)}</code></td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.test_type)}</td><td>${esc(r.result)}</td><td>${esc([r.reagent,r.reagent_lot].filter(Boolean).join(' · ')||'—')}</td><td>${esc(r.status)}</td></tr>`).join(''):'<tr><td colspan="7">Sin histórico individual.</td></tr>'}catch(e){document.getElementById('scr-msg').innerHTML=`<div class="status warn">${esc(e.message)}</div>`}}
 await load();
}
