import { bloodData } from './blood-operations-data.js';
import { commandData } from './command-data.js';
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
const n=v=>Number(v||0);

export async function mountScreening(root){
 const branches=await bloodData.branches(),bm=Object.fromEntries(branches.map(b=>[b.id,b.name]));
 root.innerHTML=`<div class="sales-toolbar"><div><h2 class="section-heading">Tamizaje por lotes</h2><div class="muted">La captura individual de resultados está inactiva. El trabajo operativo se registra por lote/tanda en el Reporte Operativo Diario.</div></div><a class="secondary" href="#dailyinventory">Abrir reporte diario</a></div>
 <div id="scr-msg"></div>
 <section class="card quick-capture"><div class="quick-capture-head"><div><div class="eyebrow">Modelo vigente</div><h3>Lotes diarios</h3></div><span class="state-pill state-info">CAPTURA CONSOLIDADA</span></div><div class="filter-grid"><label>Sucursal<select id="scr-branch"><option value="">Todas</option>${branches.map(b=>`<option value="${esc(b.id)}">${esc(b.name)}</option>`).join('')}</select></label><label>Fecha desde<input id="scr-from" type="date"></label><label>Fecha hasta<input id="scr-to" type="date"></label></div><p class="muted">Registre por lote: recibidos, no reactivos, reactivos, pendientes y descartados. No se solicita una fila por cada unidad.</p></section>
 <section class="ops-section"><div class="ops-kpi-grid" id="scr-kpis"></div></section>
 <section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Sucursal</th><th>Lote / tanda</th><th>Recibidos</th><th>No reactivos</th><th>Reactivos</th><th>Pendientes</th><th>Descartados</th><th>Balance</th></tr></thead><tbody id="scr-lots"></tbody></table></div></section>
 <details class="card"><summary><strong>Histórico técnico individual — solo consulta</strong></summary><p class="muted">Se conserva para trazabilidad histórica; no es el flujo operativo principal.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Fecha</th><th>Unidad</th><th>Sucursal</th><th>Prueba</th><th>Resultado</th><th>Reactivo/Lote</th><th>Estado</th></tr></thead><tbody id="scr-body"></tbody></table></div></details>`;
 let lotRows=[],legacy=[];
 function kpi(label,value){return `<section class="card ops-kpi-card"><div class="muted">${label}</div><div class="kpi">${value}</div></section>`}
 function render(){const branch=document.getElementById('scr-branch').value,from=document.getElementById('scr-from').value,to=document.getElementById('scr-to').value;const rows=lotRows.filter(x=>(!branch||x.branch_id===branch)&&(!from||x.date>=from)&&(!to||x.date<=to));document.getElementById('scr-lots').innerHTML=rows.length?rows.map(x=>{const balance=n(x.received)-(n(x.non_reactive)+n(x.reactive)+n(x.pending)+n(x.discarded));return `<tr><td>${esc(x.date)}</td><td>${esc(bm[x.branch_id]||x.branch_id)}</td><td><strong>${esc(x.lot||'—')}</strong></td><td>${n(x.received)}</td><td>${n(x.non_reactive)}</td><td>${n(x.reactive)}</td><td>${n(x.pending)}</td><td>${n(x.discarded)}</td><td>${balance===0?'<span class="state-pill state-ok">OK</span>':`<span class="state-pill state-warn">${balance}</span>`}</td></tr>`}).join(''):'<tr><td colspan="9">Sin lotes diarios registrados.</td></tr>';const totals=rows.reduce((a,x)=>({received:a.received+n(x.received),non:a.non+n(x.non_reactive),reactive:a.reactive+n(x.reactive),pending:a.pending+n(x.pending),discarded:a.discarded+n(x.discarded)}),{received:0,non:0,reactive:0,pending:0,discarded:0});document.getElementById('scr-kpis').innerHTML=kpi('Lotes',rows.length)+kpi('Recibidos',totals.received)+kpi('Reactivos',totals.reactive)+kpi('Pendientes',totals.pending);const legacyFiltered=legacy.filter(r=>(!branch||r.branch_id===branch)&&(!from||r.screening_date>=from)&&(!to||r.screening_date<=to));document.getElementById('scr-body').innerHTML=legacyFiltered.length?legacyFiltered.map(r=>`<tr><td>${esc(r.screening_date)}</td><td><code>${esc(r.source_unit_code)}</code></td><td>${esc(bm[r.branch_id]||r.branch_id)}</td><td>${esc(r.test_type)}</td><td>${esc(r.result)}</td><td>${esc([r.reagent,r.reagent_lot].filter(Boolean).join(' · ')||'—')}</td><td>${esc(r.status)}</td></tr>`).join(''):'<tr><td colspan="7">Sin histórico individual.</td></tr>'}
 async function load(){try{const [reports,legacyRows]=await Promise.all([commandData.recentCloses(60),bloodData.screenings()]);lotRows=[];for(const r of reports){for(const l of (Array.isArray(r.screening_lots)?r.screening_lots:[])){lotRows.push({...l,date:r.close_date,branch_id:r.branch_id,status:r.status})}}legacy=legacyRows;render()}catch(e){document.getElementById('scr-msg').innerHTML=`<div class="status warn">${esc(e.message)}</div>`}}
 ['scr-branch','scr-from','scr-to'].forEach(id=>document.getElementById(id).addEventListener('change',render));await load();
}
